# Generated by Django 3.1.7 on 2021-03-13 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('tags', models.ManyToManyField(to='map.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date_start', models.DateField(auto_now=True)),
                ('date_end', models.DateField(auto_now=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('share_status', models.SmallIntegerField(choices=[(1, 'everyone can see'), (2, 'anyone with link'), (3, 'only specific users'), (9, 'blocked')], default=1, verbose_name='share status')),
                ('edit_status', models.SmallIntegerField(choices=[(1, 'Everyone can edit'), (2, 'Only editors can edit'), (3, 'Only owner can edit')], default=3, verbose_name='edit status')),
                ('edit_users', models.ManyToManyField(blank=True, related_name='maps_editor', to=settings.AUTH_USER_MODEL, verbose_name='edit users')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maps_owner', to=settings.AUTH_USER_MODEL)),
                ('share_users', models.ManyToManyField(blank=True, related_name='maps_shared', to=settings.AUTH_USER_MODEL, verbose_name='share users')),
            ],
        ),
    ]
