# Generated by Django 3.1.7 on 2021-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_text', models.TextField()),
                ('event_start', models.DateTimeField(verbose_name='event start')),
                ('event_end', models.DateTimeField(verbose_name='event end')),
            ],
        ),
    ]
