# Generated by Django 3.1.7 on 2021-03-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_start',
            field=models.DateField(),
        ),
    ]
