# Generated by Django 3.1.7 on 2021-03-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20210313_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='skill',
            new_name='tag',
        ),
    ]
