# Generated by Django 3.1.7 on 2021-03-13 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0006_auto_20210313_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='owner',
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='edit_status',
            field=models.SmallIntegerField(choices=[(1, 'Everyone can edit'), (2, 'Only editors can edit')], default=3, verbose_name='edit status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='share_users',
            field=models.ManyToManyField(blank=True, related_name='events_shared', to=settings.AUTH_USER_MODEL, verbose_name='share with'),
        ),
        migrations.AlterField(
            model_name='place',
            name='edit_status',
            field=models.SmallIntegerField(choices=[(1, 'Everyone can edit'), (2, 'Only editors can edit')], default=3, verbose_name='edit status'),
        ),
        migrations.AlterField(
            model_name='place',
            name='edit_users',
            field=models.ManyToManyField(blank=True, related_name='places_editor', to=settings.AUTH_USER_MODEL, verbose_name='editors'),
        ),
        migrations.AlterField(
            model_name='place',
            name='share_users',
            field=models.ManyToManyField(blank=True, related_name='places_shared', to=settings.AUTH_USER_MODEL, verbose_name='share with'),
        ),
    ]
