# Generated by Django 3.1.7 on 2021-03-13 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0009_auto_20210313_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='share_status',
            field=models.SmallIntegerField(choices=[(1, 'everyone can see'), (2, 'anyone with link'), (3, 'only specific users')], default=1, verbose_name='share status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='share_users',
            field=models.ManyToManyField(blank=True, related_name='shared_events', to=settings.AUTH_USER_MODEL, verbose_name='share with'),
        ),
        migrations.AlterField(
            model_name='place',
            name='share_status',
            field=models.SmallIntegerField(choices=[(1, 'everyone can see'), (2, 'anyone with link'), (3, 'only specific users')], default=1, verbose_name='share status'),
        ),
        migrations.AlterField(
            model_name='place',
            name='share_users',
            field=models.ManyToManyField(blank=True, related_name='shared_places', to=settings.AUTH_USER_MODEL, verbose_name='share with'),
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('share_status', models.SmallIntegerField(choices=[(1, 'everyone can see'), (2, 'anyone with link'), (3, 'only specific users')], default=1, verbose_name='share status')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_positions', to=settings.AUTH_USER_MODEL)),
                ('share_users', models.ManyToManyField(blank=True, related_name='shared_positions', to=settings.AUTH_USER_MODEL, verbose_name='share with')),
            ],
        ),
    ]
