# Generated by Django 3.1.7 on 2021-03-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20210313_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userposition',
            old_name='creator',
            new_name='user',
        ),
    ]
