# Generated by Django 3.1.7 on 2021-03-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_auto_20210315_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
