# Generated by Django 3.1.7 on 2021-03-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_auto_20210327_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#000', max_length=100),
        ),
    ]
