# Generated by Django 3.1.7 on 2021-04-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_tag_prio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
