# Generated by Django 3.1.7 on 2021-04-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to='map.Offer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='offers', to='map.Offer'),
        ),
    ]
